### ISSUE TITLE
`Unknown type to decode: T :: AccountId` && ` AccountIndex`

### ISSUE THREAD

**Issue by gnunicorn** [paritytech/substrate-ui#11]
Running the substrate dev chain, starting up after #9 the UI appears, however the console shows the errors:
`Uncaught Unknown type to decode: T :: AccountId` and `Uncaught Unknown type to decode: T :: AccountIndex`

The later repeatedly when I try to interact (lookup account or add account to wallet). Screenshot with Traceback in chrome (same in firefox):

![screenshot-20181214164138-2356x560](https://user-images.githubusercontent.com/40496/50012510-263a6e00-ffbf-11e8-96dd-87b86eadf49b.png)

**Comment by shawntabrizi** [comment]
Stale.
