### ISSUE TITLE
Unable to easily validate with account created via the Substrate UI

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate-ui#2]
[Question below was posted in Polkadot Watercooler](https://matrix.to/#/!fOOzymDEHiIIUtmlBE:matrix.org/$15394477973204GVUqo:matrix.parity.io)

> "if create a wallet with Gav's Substrate UI https://paritytech.github.io/substrate-ui/index.html, the wallet has a "seed" phrase that accompanies the key.
> when we start a substrate node, and assuming we're a validator, do we provide that "seed" as the value of the --key flag (which is for specifying additional key seeds). also, would we ever use the --node-key flag with a "bbq birch" node (which requires a 64-character hex string node secret key)? or do we only use that flag with "krumme lanke"?, i.e.
> 
> ```
> ./target/release/substrate --name "my bbq birch name" \
>   --telemetry-url ws://telemetry.polkadot.io:1024 \
>   --key "really long seed phrase associated with wallet and provided in gavs substrate ui"
>   --validator
> ```

Response from Gav was that:

> currently you can’t easily validate with an account created via the ui. For that, I either need to export the ed25519 seed as hex (easy) or build in bip39 derivation into the node (correct)

**Comment by gavofyork** [comment]
Done.
