### ISSUE TITLE
substrate-ui shows blank page when comes to 127.0.0.1:8000

### ISSUE THREAD

**Issue by Rkrushanovskij** [paritytech/substrate-ui#4]
I tried to explore substrate technology and wanted to go same way as @gavofyork on the Web3 Summit. 
I started substrate project with `substrate --dev`, block generating started successfully. 
After that i started substrate-ui project with `npm run dev`, server started successfully and no errors shown.
But when i come to 127.0.0.1:8000, there is blank page.Console shows many errors related to webpack:
[substrate-ui-browser-logs.txt](https://github.com/paritytech/substrate-ui/files/2543115/substrate-ui-browser-logs.txt)
Webpack dependency installed and exists in `node_modules` folder.
Ports usage shown that port 9944 used by `substrate` and port 8000 used by `node`.
Does it my mistakes or bug in repository?

P.S. also, there are no `yarn` scenarious in repo but in README.md written instructions using it...

**Comment by AlexMikhalev** [comment]
Hello @Rkrushanovskij, I have the same issue, how did you resolve it?

**Comment by Rkrushanovskij** [comment]
Hi @AlexMikhalev . I don\`t remember exactly what was the problem - i just re-do it correctly and it became worked. Parity Technologies published guide about how to do it - https://twitter.com/ParityTech/status/1061303995636084736
I discovered it from Telegram channel - don`t you want to join too and be in touch with all news from Parity Technologies? https://t.me/parity_technologies
