### ISSUE TITLE
TypeError: Expected Buffer

### ISSUE THREAD

**Issue by attente** [paritytech/substrate-ui#9]
Trying to go through the tutorial [here](https://substrate.readme.io/docs/creating-a-custom-substrate-chain) for creating a custom Substrate chain and encountering a blank page when trying to launch the UI with these errors in the JS console:

> TypeError: Expected Buffer bundle.js line 349 > eval:29:41
encode
webpack:///./node_modules/base-x/index.js?:29:41
ss58Encode
webpack:///./node_modules/oo7-substrate/src/ss58.js?:43:9
_sync/this._keys<
webpack:///./node_modules/oo7-substrate/src/secretStore.js?:95:18
map self-hosted:286:17 _sync
webpack:///./node_modules/oo7-substrate/src/secretStore.js?:91:16
_load
webpack:///./node_modules/oo7-substrate/src/secretStore.js?:85:3
SecretStore
webpack:///./node_modules/oo7-substrate/src/secretStore.js?:23:3
secretStore
webpack:///./node_modules/oo7-substrate/src/secretStore.js?:112:19
WalletList
webpack:///./src/WalletList.jsx?:68:17
constructClassInstance
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12484:18
updateClassComponent
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:14255:5
beginWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:15082:16
performUnitOfWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17820:12
workLoop
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17860:24
callCallback
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:149:9
invokeGuardedCallbackDev
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:199:7
invokeGuardedCallback
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:256:3
replayUnitOfWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17107:5
renderRoot
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:17979:13
performWorkOnRoot
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18837:7
performWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18749:7
performSyncWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18723:3
requestWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18592:5
scheduleWork
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18401:5
enqueueSetState
webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:12313:5
Component.prototype.setState
webpack:///./node_modules/react/cjs/react.development.js?:372:3
initProps/this._consolidatedExtraBonds<
webpack:///./node_modules/oo7-react/lib/index.js?:188:5
<anonymous> self-hosted:975:17 _notified
webpack:///./node_modules/oo7/src/reactiveBond.js?:255:4
_notified self-hosted:973:17 trigger/<
webpack:///./node_modules/oo7/src/bond.js?:319:53
forEach self-hosted:262:13 trigger
webpack:///./node_modules/oo7/src/bond.js?:319:33
initialise/<
webpack:///./node_modules/oo7-substrate/src/bonds.js?:61:21
initialiseFromMetadata/<
webpack:///./node_modules/oo7-substrate/src/bonds.js?:127:38
forEach self-hosted:262:13 initialiseFromMetadata
webpack:///./node_modules/oo7-substrate/src/bonds.js?:127:2
The above error occurred in the <WalletList> component:
    in WalletList (created by App)
    in div (created by App)
    in div (created by Segment)
    in Segment (created by App)
    in div (created by App)
    in App

> Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. react-dom.development.js:15749:5
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in InputBond (created by App)
    in div (created by App)
    in div (created by Segment)
    in Segment (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in AccountIdBond (created by App)
    in div (created by App)
    in div (created by Segment)
    in Segment (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
TypeError: Expected Buffer bundle.js line 349 > eval:29:41
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Pretty (created by App)
    in div (created by LabelDetail)
    in LabelDetail (created by App)
    in div (created by Label)
    in Label (created by App)
    in div (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in SignerBond (created by App)
    in div (created by App)
    in div (created by Segment)
    in Segment (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
TypeError: Expected Buffer bundle.js line 349 > eval:29:41
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in BalanceBond (created by App)
    in div (created by App)
    in div (created by Segment)
    in Segment (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Rspan (created by App)
    in div (created by LabelDetail)
    in LabelDetail (created by App)
    in div (created by Label)
    in Label (created by App)
    in div (created by App)
    in div (created by App)
    in App react-dom.development.js:506:7
TypeError: Expected Buffer bundle.js line 349 > eval:29:41

**Comment by adetante** [comment]
The problem is in the package oo7-substrate, [following the switch to version 3.0.5 on base-x](https://github.com/paritytech/oo7/commit/6328b70d29f59608d25b97d597f6b1f1a8449c7e).

As a workaround, you can add this at the end of `package.json`
```
"resolutions": {
  "**/base-x": "3.0.4"
}
```
and then run `yarn install`

**Comment by gnunicorn** [comment]
This is still the case on `master` and said patch still makes it work. Reopening.

**Comment by zzh33cn** [comment]
is this issue closed? i face the same problem.what's wrong?

**Comment by shawntabrizi** [comment]
Stale.
